version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./app:/app

  mongo-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    depends_on:
      - mongo-db

volumes:
  mongo-db-data: