version: '3.1'

services:

  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: SCA_ITS
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: Dev@1234
    ports:
      - 3307:3306
    volumes:
      - ./dbData:/var/lib/mysql
    networks:
      - my-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - my-network
  # app:
  #   build:
  #     context: .
  #     dockerfile: app.Dockerfile
  #   restart: always
  #   depends_on:
  #     db:
  #       condition: service_started
  #   ports:
  #     - 5000:5000
  #   expose:
  #     - 5000
  #   networks:
  #     - my-network

networks:
  my-network:
    name: bcity-test-network
