version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_app
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3360:3306"
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  db-data:
